# Generated by Django 4.0 on 2022-01-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clash', '0006_alter_submission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='memory_limit',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='time_limit',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
