# Generated by Django 3.2.9 on 2022-02-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clash', '0007_question_memory_limit_question_time_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='memory_limit',
        ),
        migrations.RemoveField(
            model_name='question',
            name='time_limit',
        ),
        migrations.AddField(
            model_name='question',
            name='constraints',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='input_format',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='output_format',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='sample_input',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='sample_output',
            field=models.TextField(null=True),
        ),
    ]
