# Generated by Django 3.2.9 on 2022-01-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clash', '0003_auto_20211205_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('WA', 'Wrong Answer'), ('AC', 'Accepted'), ('TLE', 'Time Limit Exceeded'), ('CTE', 'Compile Time Error'), ('RTE', 'Run Time Error')], max_length=10, null=True),
        ),
    ]
