# Generated by Django 3.2.9 on 2022-04-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clash', '0008_auto_20220216_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explaination',
            field=models.TextField(null=True),
        ),
    ]
