# Generated by Django 3.2.3 on 2021-11-30 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('junior', models.BooleanField(null=True)),
                ('total_score', models.IntegerField(default=0, null=True)),
                ('ques1', models.IntegerField(default=0, null=True)),
                ('ques2', models.IntegerField(default=0, null=True)),
                ('ques3', models.IntegerField(default=0, null=True)),
                ('ques4', models.IntegerField(default=0, null=True)),
                ('ques5', models.IntegerField(default=0, null=True)),
                ('ques6', models.IntegerField(default=0, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1003, null=True)),
                ('body', models.TextField(null=True)),
                ('correct_submissions', models.IntegerField(null=True)),
                ('total_submissions', models.IntegerField(null=True)),
                ('accuracy', models.FloatField(null=True)),
                ('junior', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='testcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tc_input', models.FileField(null=True, upload_to='Question_Data/Input')),
                ('tc_output', models.FileField(null=True, upload_to='Question_Data/Output')),
                ('q_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clash.question')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('code', models.TextField(null=True)),
                ('status', models.CharField(choices=[('WA', 'Wrong Answer'), ('AC', 'Accepted'), ('TLE', 'Time Limit Exceeded'), ('CTE', 'Compile Time Error')], max_length=10, null=True)),
                ('language', models.CharField(choices=[('c', 'C'), ('cpp', 'C++'), ('py', 'Python')], max_length=10, null=True)),
                ('p_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clash.player')),
                ('q_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clash.question')),
            ],
        ),
    ]
