# Generated by Django 3.2.3 on 2021-12-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rc', '0002_rcquestion_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rcquestion',
            name='code',
            field=models.TextField(null=True),
        ),
    ]
